In [1]:
from typing import Literal
import panel as pn
import numpy as np
from icsa import ICSA, set_seeds
from classification_icsa import load_metadata, MCC, load_knn_metadata, load_sgd_metadata, get_confusion, get_performance_data

pn.extension('plotly')
pn.config.theme = 'dark'
set_seeds(0)

In [2]:
# KNN #
knn_fpath = 'analysis/classification/knn/'  # filepath for analysis files

def fit_overlapping(metadata, model_fpath_overlapping: str, optim_dir: Literal['min', 'max'], save=True, validation_split=0.1, epochs=150, verbose=0, **kwargs):
    analysis_overlapping = ICSA(optim_dir, mode='overlay', **kwargs)  # ICSA with overlapping spaces
    analysis_overlapping.fit_show(model_fpath_overlapping, metadata, validation_split=validation_split, epochs=epochs, save=save, verbose=verbose)
    return analysis_overlapping# fit

## MCC ##
knn_metadata_mcc = load_knn_metadata(knn_fpath, confusion_function=MCC)

In [5]:
analysis_overlapping = ICSA('max', mode='overlay')  # ICSA with overlayed spaces

In [6]:
analysis_overlapping.load_fitted_model(knn_fpath + 'mcc/overlapping/', knn_metadata_mcc.feature_data, knn_metadata_mcc.parameter_data)

In [7]:
import numpy as np
isIG1 = (analysis_overlapping._z[:, 1] >= 0.15).tolist()

In [9]:
import pandas as pd
IGsources = pd.Series(np.array(["IG1" if x else "IG2" for x in isIG1]))

In [10]:
IGsources

0      IG1
1      IG2
2      IG2
3      IG1
4      IG2
      ...
230    IG2
231    IG1
232    IG1
233    IG2
234    IG2
Length: 235, dtype: object

In [11]:
analysis_overlapping._feature_data

,Max_Normalized_Entropy_attributes,Normalized_Entropy_Class_Attribute,Mean_Mutual_Information_Attribute_Class,ErrorRate_Decision_Node,WeightedDist_StdDev,Max_Feature_Efficiency_F3,Collective_Feature_Efficiency_F4,Training_Error_Linear_Classifier_L2,Fraction_Points_Class_Boundary_N1,Nonlinearity_Nearest_Neighbor_Classifier_N4
Row,,,,,,,,,,
abalone,0.291428,-0.023151,0.907839,1.207553,0.681170,-0.871446,-1.247791,1.058079,1.157236,1.231493
abalone_ori,0.291428,1.326100,1.422140,-0.148358,0.681170,0.857186,-0.116430,-1.150660,-0.772155,1.414517
appendicitis,-0.587054,-0.347641,0.006819,-0.718312,-0.753902,0.182074,0.427543,0.616152,0.640470,0.429404
asbestos,-0.176235,0.690571,0.371398,-0.076535,-0.653789,-0.543228,-1.159402,0.242225,0.955694,0.978861
audiology_std,-1.012659,1.847443,-0.045760,0.092628,-0.837206,1.548439,1.037583,-1.210021,-1.150055,-1.239337
...,...,...,...,...,...,...,...,...,...,...
winsconsin,-0.378746,-0.455065,1.377326,-1.159989,1.238669,-0.612091,-0.904715,-1.202555,-0.974435,-1.159108
wpbc,-0.414613,-0.391342,-1.175199,0.073002,-0.657042,-0.324125,1.107740,0.906364,1.234674,0.673640
wpbc_no_Nas,-0.385618,-0.386470,-1.183380,0.058286,-0.657042,-0.306293,1.122470,0.904567,1.228554,0.691551
yeast,0.148695,0.948255,0.289946,0.655603,0.873359,0.339756,-0.288481,-0.317731,-0.283316,0.607554
zoo,-0.386257,1.591654,1.499694,0.212721,-0.501008,1.388641,0.874790,-1.114443,-1.099962,-1.376163

In [33]:
instance_data = analysis_overlapping._feature_data.copy()

In [34]:
IGsources.index = instance_data.index

In [35]:
instance_data

,Max_Normalized_Entropy_attributes,Normalized_Entropy_Class_Attribute,Mean_Mutual_Information_Attribute_Class,ErrorRate_Decision_Node,WeightedDist_StdDev,Max_Feature_Efficiency_F3,Collective_Feature_Efficiency_F4,Training_Error_Linear_Classifier_L2,Fraction_Points_Class_Boundary_N1,Nonlinearity_Nearest_Neighbor_Classifier_N4
Row,,,,,,,,,,
abalone,0.291428,-0.023151,0.907839,1.207553,0.681170,-0.871446,-1.247791,1.058079,1.157236,1.231493
abalone_ori,0.291428,1.326100,1.422140,-0.148358,0.681170,0.857186,-0.116430,-1.150660,-0.772155,1.414517
appendicitis,-0.587054,-0.347641,0.006819,-0.718312,-0.753902,0.182074,0.427543,0.616152,0.640470,0.429404
asbestos,-0.176235,0.690571,0.371398,-0.076535,-0.653789,-0.543228,-1.159402,0.242225,0.955694,0.978861
audiology_std,-1.012659,1.847443,-0.045760,0.092628,-0.837206,1.548439,1.037583,-1.210021,-1.150055,-1.239337
...,...,...,...,...,...,...,...,...,...,...
winsconsin,-0.378746,-0.455065,1.377326,-1.159989,1.238669,-0.612091,-0.904715,-1.202555,-0.974435,-1.159108
wpbc,-0.414613,-0.391342,-1.175199,0.073002,-0.657042,-0.324125,1.107740,0.906364,1.234674,0.673640
wpbc_no_Nas,-0.385618,-0.386470,-1.183380,0.058286,-0.657042,-0.306293,1.122470,0.904567,1.228554,0.691551
yeast,0.148695,0.948255,0.289946,0.655603,0.873359,0.339756,-0.288481,-0.317731,-0.283316,0.607554
zoo,-0.386257,1.591654,1.499694,0.212721,-0.501008,1.388641,0.874790,-1.114443,-1.099962,-1.376163

In [36]:
instance_data = pd.concat([IGsources, instance_data], axis=1)

In [37]:
instance_data

,0,Max_Normalized_Entropy_attributes,Normalized_Entropy_Class_Attribute,Mean_Mutual_Information_Attribute_Class,ErrorRate_Decision_Node,WeightedDist_StdDev,Max_Feature_Efficiency_F3,Collective_Feature_Efficiency_F4,Training_Error_Linear_Classifier_L2,Fraction_Points_Class_Boundary_N1,Nonlinearity_Nearest_Neighbor_Classifier_N4
Row,,,,,,,,,,,
abalone,IG1,0.291428,-0.023151,0.907839,1.207553,0.681170,-0.871446,-1.247791,1.058079,1.157236,1.231493
abalone_ori,IG2,0.291428,1.326100,1.422140,-0.148358,0.681170,0.857186,-0.116430,-1.150660,-0.772155,1.414517
appendicitis,IG2,-0.587054,-0.347641,0.006819,-0.718312,-0.753902,0.182074,0.427543,0.616152,0.640470,0.429404
asbestos,IG1,-0.176235,0.690571,0.371398,-0.076535,-0.653789,-0.543228,-1.159402,0.242225,0.955694,0.978861
audiology_std,IG2,-1.012659,1.847443,-0.045760,0.092628,-0.837206,1.548439,1.037583,-1.210021,-1.150055,-1.239337
...,...,...,...,...,...,...,...,...,...,...,...
winsconsin,IG2,-0.378746,-0.455065,1.377326,-1.159989,1.238669,-0.612091,-0.904715,-1.202555,-0.974435,-1.159108
wpbc,IG1,-0.414613,-0.391342,-1.175199,0.073002,-0.657042,-0.324125,1.107740,0.906364,1.234674,0.673640
wpbc_no_Nas,IG1,-0.385618,-0.386470,-1.183380,0.058286,-0.657042,-0.306293,1.122470,0.904567,1.228554,0.691551
yeast,IG2,0.148695,0.948255,0.289946,0.655603,0.873359,0.339756,-0.288481,-0.317731,-0.283316,0.607554
zoo,IG2,-0.386257,1.591654,1.499694,0.212721,-0.501008,1.388641,0.874790,-1.114443,-1.099962,-1.376163

In [38]:
instance_data.rename(columns={0: "Instance Group"}, inplace=True)

In [39]:
instance_data

,Instance Group,Max_Normalized_Entropy_attributes,Normalized_Entropy_Class_Attribute,Mean_Mutual_Information_Attribute_Class,ErrorRate_Decision_Node,WeightedDist_StdDev,Max_Feature_Efficiency_F3,Collective_Feature_Efficiency_F4,Training_Error_Linear_Classifier_L2,Fraction_Points_Class_Boundary_N1,Nonlinearity_Nearest_Neighbor_Classifier_N4
Row,,,,,,,,,,,
abalone,IG1,0.291428,-0.023151,0.907839,1.207553,0.681170,-0.871446,-1.247791,1.058079,1.157236,1.231493
abalone_ori,IG2,0.291428,1.326100,1.422140,-0.148358,0.681170,0.857186,-0.116430,-1.150660,-0.772155,1.414517
appendicitis,IG2,-0.587054,-0.347641,0.006819,-0.718312,-0.753902,0.182074,0.427543,0.616152,0.640470,0.429404
asbestos,IG1,-0.176235,0.690571,0.371398,-0.076535,-0.653789,-0.543228,-1.159402,0.242225,0.955694,0.978861
audiology_std,IG2,-1.012659,1.847443,-0.045760,0.092628,-0.837206,1.548439,1.037583,-1.210021,-1.150055,-1.239337
...,...,...,...,...,...,...,...,...,...,...,...
winsconsin,IG2,-0.378746,-0.455065,1.377326,-1.159989,1.238669,-0.612091,-0.904715,-1.202555,-0.974435,-1.159108
wpbc,IG1,-0.414613,-0.391342,-1.175199,0.073002,-0.657042,-0.324125,1.107740,0.906364,1.234674,0.673640
wpbc_no_Nas,IG1,-0.385618,-0.386470,-1.183380,0.058286,-0.657042,-0.306293,1.122470,0.904567,1.228554,0.691551
yeast,IG2,0.148695,0.948255,0.289946,0.655603,0.873359,0.339756,-0.288481,-0.317731,-0.283316,0.607554
zoo,IG2,-0.386257,1.591654,1.499694,0.212721,-0.501008,1.388641,0.874790,-1.114443,-1.099962,-1.376163

In [41]:
instance_data_PR = instance_data.copy()

In [42]:
instance_data_PR

,Instance Group,Max_Normalized_Entropy_attributes,Normalized_Entropy_Class_Attribute,Mean_Mutual_Information_Attribute_Class,ErrorRate_Decision_Node,WeightedDist_StdDev,Max_Feature_Efficiency_F3,Collective_Feature_Efficiency_F4,Training_Error_Linear_Classifier_L2,Fraction_Points_Class_Boundary_N1,Nonlinearity_Nearest_Neighbor_Classifier_N4
Row,,,,,,,,,,,
abalone,IG1,0.291428,-0.023151,0.907839,1.207553,0.681170,-0.871446,-1.247791,1.058079,1.157236,1.231493
abalone_ori,IG2,0.291428,1.326100,1.422140,-0.148358,0.681170,0.857186,-0.116430,-1.150660,-0.772155,1.414517
appendicitis,IG2,-0.587054,-0.347641,0.006819,-0.718312,-0.753902,0.182074,0.427543,0.616152,0.640470,0.429404
asbestos,IG1,-0.176235,0.690571,0.371398,-0.076535,-0.653789,-0.543228,-1.159402,0.242225,0.955694,0.978861
audiology_std,IG2,-1.012659,1.847443,-0.045760,0.092628,-0.837206,1.548439,1.037583,-1.210021,-1.150055,-1.239337
...,...,...,...,...,...,...,...,...,...,...,...
winsconsin,IG2,-0.378746,-0.455065,1.377326,-1.159989,1.238669,-0.612091,-0.904715,-1.202555,-0.974435,-1.159108
wpbc,IG1,-0.414613,-0.391342,-1.175199,0.073002,-0.657042,-0.324125,1.107740,0.906364,1.234674,0.673640
wpbc_no_Nas,IG1,-0.385618,-0.386470,-1.183380,0.058286,-0.657042,-0.306293,1.122470,0.904567,1.228554,0.691551
yeast,IG2,0.148695,0.948255,0.289946,0.655603,0.873359,0.339756,-0.288481,-0.317731,-0.283316,0.607554
zoo,IG2,-0.386257,1.591654,1.499694,0.212721,-0.501008,1.388641,0.874790,-1.114443,-1.099962,-1.376163

In [44]:
orig_features = analysis_overlapping._feature_data.copy()

In [45]:
orig_features

,Max_Normalized_Entropy_attributes,Normalized_Entropy_Class_Attribute,Mean_Mutual_Information_Attribute_Class,ErrorRate_Decision_Node,WeightedDist_StdDev,Max_Feature_Efficiency_F3,Collective_Feature_Efficiency_F4,Training_Error_Linear_Classifier_L2,Fraction_Points_Class_Boundary_N1,Nonlinearity_Nearest_Neighbor_Classifier_N4
Row,,,,,,,,,,
abalone,0.291428,-0.023151,0.907839,1.207553,0.681170,-0.871446,-1.247791,1.058079,1.157236,1.231493
abalone_ori,0.291428,1.326100,1.422140,-0.148358,0.681170,0.857186,-0.116430,-1.150660,-0.772155,1.414517
appendicitis,-0.587054,-0.347641,0.006819,-0.718312,-0.753902,0.182074,0.427543,0.616152,0.640470,0.429404
asbestos,-0.176235,0.690571,0.371398,-0.076535,-0.653789,-0.543228,-1.159402,0.242225,0.955694,0.978861
audiology_std,-1.012659,1.847443,-0.045760,0.092628,-0.837206,1.548439,1.037583,-1.210021,-1.150055,-1.239337
...,...,...,...,...,...,...,...,...,...,...
winsconsin,-0.378746,-0.455065,1.377326,-1.159989,1.238669,-0.612091,-0.904715,-1.202555,-0.974435,-1.159108
wpbc,-0.414613,-0.391342,-1.175199,0.073002,-0.657042,-0.324125,1.107740,0.906364,1.234674,0.673640
wpbc_no_Nas,-0.385618,-0.386470,-1.183380,0.058286,-0.657042,-0.306293,1.122470,0.904567,1.228554,0.691551
yeast,0.148695,0.948255,0.289946,0.655603,0.873359,0.339756,-0.288481,-0.317731,-0.283316,0.607554
zoo,-0.386257,1.591654,1.499694,0.212721,-0.501008,1.388641,0.874790,-1.114443,-1.099962,-1.376163

In [48]:
from sklearn.preprocessing import QuantileTransformer

qt = QuantileTransformer(output_distribution="uniform")

In [ ]:
quantile_features = qt.fit_transform(orig_features)

In [53]:
quantile_features[:, 0]

array([0.84188034, 0.84188034, 0.17521368, 0.28205128, 0.10683761,
       0.32905983, 0.        , 0.73504274, 0.57264957, 0.26495726,
       0.82051282, 0.32478632, 0.44017094, 0.63675214, 0.31196581,
       0.27350427, 0.26923077, 1.        , 0.55982906, 0.09401709,
       0.71367521, 0.82478632, 0.11111111, 0.44444444, 0.7991453 ,
       0.92307692, 0.90598291, 0.20940171, 0.23076923, 0.56837607,
       0.94444444, 0.16666667, 0.16666667, 0.86324786, 0.        ,
       0.39957265, 0.39957265, 0.        , 0.42307692, 0.42307692,
       0.31623932, 1.        , 1.        , 0.72222222, 0.        ,
       0.8974359 , 0.        , 0.        , 0.2008547 , 0.95726496,
       0.52564103, 0.91239316, 0.92948718, 0.92948718, 0.61111111,
       0.52991453, 0.38461538, 0.38888889, 0.0982906 , 0.23931624,
       0.17948718, 0.        , 0.81196581, 0.        , 0.83333333,
       0.44871795, 0.78205128, 0.78632479, 0.19230769, 0.71794872,
       0.64529915, 0.37606838, 0.77350427, 0.56410256, 0.75641026,
       0.81623932, 0.38034188, 0.8034188 , 0.7008547 , 0.5042735 ,
       0.58547009, 0.87179487, 0.47863248, 0.64957265, 0.77777778,
       0.35470085, 0.87606838, 0.26068376, 0.08974359, 0.27777778,
       0.28632479, 0.29059829, 0.94871795, 0.11538462, 0.11965812,
       0.20512821, 0.94017094, 0.33333333, 0.29487179, 0.95299145,
       0.96581197, 0.96153846, 0.88461538, 0.67735043, 0.67735043,
       0.68803419, 0.40598291, 0.40598291, 0.51282051, 0.53846154,
       0.79059829, 0.1025641 , 0.82905983, 0.36324786, 0.61965812,
       0.91239316, 0.92948718, 1.        , 0.        , 0.88034188,
       0.73931624, 0.86324786, 0.85897436, 0.9017094 , 0.89316239,
       0.88888889, 0.5       , 0.34188034, 0.4957265 , 0.52136752,
       0.6965812 , 0.68376068, 0.17094017, 0.        , 0.        ,
       0.        , 0.        , 0.54273504, 0.08547009, 0.41880342,
       0.45299145, 0.43589744, 0.12393162, 0.55128205, 0.70512821,
       0.55555556, 0.70940171, 0.65384615, 0.74358974, 0.41452991,
       0.21794872, 0.76068376, 0.        , 0.69230769, 0.74786325,
       0.14102564, 0.14102564, 0.14102564, 0.14102564, 0.14102564,
       0.14102564, 0.14102564, 0.14102564, 0.24358974, 0.08119658,
       1.        , 0.75213675, 0.        , 0.72649573, 0.35897436,
       0.2991453 , 0.2991453 , 0.83760684, 0.61538462, 0.30769231,
       0.57905983, 0.48717949, 0.1965812 , 0.51709402, 0.48290598,
       0.80769231, 1.        , 0.63247863, 0.        , 0.37179487,
       0.91239316, 0.32051282, 0.35042735, 0.79059829, 0.57905983,
       0.49145299, 0.36752137, 0.62393162, 1.        , 0.64102564,
       0.58974359, 0.46367521, 0.5982906 , 0.5982906 , 0.46367521,
       0.5982906 , 0.46367521, 0.76709402, 0.76709402, 0.5982906 ,
       0.46367521, 0.43162393, 0.18376068, 0.18376068, 0.62820513,
       0.46367521, 0.        , 0.        , 1.        , 0.        ,
       0.73076923, 0.33760684, 0.39316239, 0.25213675, 0.25213675,
       0.66239316, 0.66666667, 0.67094017, 0.85042735, 0.85470085,
       0.50854701, 0.34615385, 0.53418803, 0.24786325, 0.65811966,
       0.23076923, 0.21367521, 0.22649573, 0.54700855, 0.22222222])

In [54]:
quantile_features

array([[0.84188034, 0.58119658, 0.77350427, ..., 0.83760684, 0.83333333,
        0.86324786],
       [0.84188034, 0.88034188, 0.89316239, ..., 0.16239316, 0.31196581,
        0.9017094 ],
       [0.17521368, 0.44017094, 0.52136752, ..., 0.69230769, 0.6965812 ,
        0.63675214],
       ...,
       [0.22649573, 0.38888889, 0.12820513, ..., 0.78205128, 0.84188034,
        0.73504274],
       [0.54700855, 0.79059829, 0.61111111, ..., 0.41025641, 0.40598291,
        0.70512821],
       [0.22222222, 0.94017094, 0.91025641, ..., 0.17094017, 0.17948718,
        0.11538462]])

In [ ]:
quantile_features

In [55]:
# Convert quantile features to DataFrame with proper index
quantile_features_df = pd.DataFrame(quantile_features, columns=orig_features.columns, index=orig_features.index)
# Add Instance Group column to the quantile features
quantile_features_df['Instance Group'] = IGsources.values
quantile_features_df

,Max_Normalized_Entropy_attributes,Normalized_Entropy_Class_Attribute,Mean_Mutual_Information_Attribute_Class,ErrorRate_Decision_Node,WeightedDist_StdDev,Max_Feature_Efficiency_F3,Collective_Feature_Efficiency_F4,Training_Error_Linear_Classifier_L2,Fraction_Points_Class_Boundary_N1,Nonlinearity_Nearest_Neighbor_Classifier_N4,Instance Group
Row,,,,,,,,,,,
abalone,0.841880,0.581197,0.773504,0.888889,0.732906,0.269231,0.183761,0.837607,0.833333,0.863248,IG1
abalone_ori,0.841880,0.880342,0.893162,0.427350,0.732906,0.730769,0.440171,0.162393,0.311966,0.901709,IG2
appendicitis,0.175214,0.440171,0.521368,0.256410,0.243590,0.564103,0.538462,0.692308,0.696581,0.636752,IG2
asbestos,0.282051,0.717949,0.649573,0.461538,0.286325,0.371795,0.235043,0.581197,0.782051,0.816239,IG1
audiology_std,0.106838,0.970085,0.500000,0.555556,0.222222,0.948718,0.735043,0.128205,0.149573,0.149573,IG2
...,...,...,...,...,...,...,...,...,...,...,...
winsconsin,0.230769,0.339744,0.884615,0.162393,0.854701,0.339744,0.282051,0.136752,0.220085,0.183761,IG2
wpbc,0.213675,0.380342,0.132479,0.534188,0.279915,0.459402,0.786325,0.786325,0.846154,0.726496,IG1
wpbc_no_Nas,0.226496,0.388889,0.128205,0.525641,0.279915,0.470085,0.803419,0.782051,0.841880,0.735043,IG1
yeast,0.547009,0.790598,0.611111,0.713675,0.790598,0.581197,0.431624,0.410256,0.405983,0.705128,IG2
zoo,0.222222,0.940171,0.910256,0.572650,0.376068,0.914530,0.675214,0.170940,0.179487,0.115385,IG2

In [56]:
# Melt the dataframe to long format for plotting
quantile_features_long = quantile_features_df.melt(
    id_vars=['Instance Group'],
    var_name='Feature',
    value_name='Percentile Rank'
)
quantile_features_long

,Instance Group,Feature,Percentile Rank
0,IG1,Max_Normalized_Entropy_attributes,0.841880
1,IG2,Max_Normalized_Entropy_attributes,0.841880
2,IG2,Max_Normalized_Entropy_attributes,0.175214
3,IG1,Max_Normalized_Entropy_attributes,0.282051
4,IG2,Max_Normalized_Entropy_attributes,0.106838
...,...,...,...
2345,IG2,Nonlinearity_Nearest_Neighbor_Classifier_N4,0.183761
2346,IG1,Nonlinearity_Nearest_Neighbor_Classifier_N4,0.726496
2347,IG1,Nonlinearity_Nearest_Neighbor_Classifier_N4,0.735043
2348,IG2,Nonlinearity_Nearest_Neighbor_Classifier_N4,0.705128
2349,IG2,Nonlinearity_Nearest_Neighbor_Classifier_N4,0.115385

In [60]:
# Calculate median for each feature by Instance Group
median_by_group = quantile_features_long.groupby(['Feature', 'Instance Group'])['Percentile Rank'].median().unstack()
median_by_group
# Calculate signed difference (IG1 - IG2)
median_difference = median_by_group['IG1'] - median_by_group['IG2']
median_difference
# Sort features by signed difference in decreasing order
sorted_features = median_difference.sort_values(ascending=False).index.tolist()
sorted_features

['Fraction_Points_Class_Boundary_N1',
 'ErrorRate_Decision_Node',
 'Training_Error_Linear_Classifier_L2',
 'Nonlinearity_Nearest_Neighbor_Classifier_N4',
 'Normalized_Entropy_Class_Attribute',
 'Max_Normalized_Entropy_attributes',
 'WeightedDist_StdDev',
 'Mean_Mutual_Information_Attribute_Class',
 'Collective_Feature_Efficiency_F4',
 'Max_Feature_Efficiency_F3']

In [64]:
import plotly.express as px
import plotly.graph_objects as go

# Create the boxplot
fig = px.box(
    quantile_features_long,
    x='Feature',
    y='Percentile Rank',
    color='Instance Group',
    category_orders={'Instance Group': ['IG1', 'IG2'],
                     'Feature': sorted_features},
    color_discrete_map={'IG1': '#636EFA', 'IG2': '#EF553B'}  # Blue for IG1, Red for IG2
)

# Update layout to match the style in the image
fig.update_layout(
    template='plotly_white',
    font=dict(size=20),
    xaxis_title='Feature',
    yaxis_title='Percentile Rank',
    yaxis=dict(tickformat='.0%'),  # Format y-axis as percentages
    height=1000,
    width=1400,
    legend=dict(
        title='Instance Group',
        yanchor="top",
        y=0.99,
        xanchor="right",
        x=0.99
    )
)

# Rotate x-axis labels for better readability
fig.update_xaxes(tickangle=45)

fig.show()

In [ ]:
# Save the figure
fig.write_image(knn_fpath + 'mcc/overlapping/instance_group_boxplots.png', engine='kaleido', width=1400, height=1000)